Algoritmo "enquanto"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 15/04/2025
Var
    contador : inteiro


Inicio
    contador <- 0
    enquanto (contador <= 10) faca
        escreval (contador)
        contador <- contador + 1
    fimenquanto

Fimalgoritmo